import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { Routes, Route, useLocation, useNavigate } from 'react-router-dom';
import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from 'framer-motion';
import { Helmet } from 'react-helmet-async';
import { Navbar, Footer } from './components/Layout';
import Chatbot from './components/Chatbot';
const Home = lazy(() => import('./pages/Home'));
const About = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.About })));
const Services = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.Services })));
const ServiceDetail = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.ServiceDetail })));
const Work = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.Work })));
const ProjectDetail = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.ProjectDetail })));
const Results = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.Results })));
const CaseStudy = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.CaseStudy })));
const Contact = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.Contact })));
const Legal = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.Legal })));
const NotFound = lazy(() => import('./pages/PublicPages').then(module => ({ default: module.NotFound })));
const AdminLayout = lazy(() => import('./admin/Admin').then(module => ({ default: module.AdminLayout })));
const AdminLogin = lazy(() => import('./admin/Admin').then(module => ({ default: module.AdminLogin })));
const Dashboard = lazy(() => import('./admin/Admin').then(module => ({ default: module.Dashboard })));
const Collection = lazy(() => import('./admin/Admin').then(module => ({ default: module.EnhancedCollection })));
const Editor = lazy(() => import('./admin/Admin').then(module => ({ default: module.ContentEditor })));
const Leads = lazy(() => import('./admin/Admin').then(module => ({ default: module.Leads })));
const SettingsPage = lazy(() => import('./admin/Admin').then(module => ({ default: module.SettingsPage })));
const MediaLibrary = lazy(() => import('./admin/Admin').then(module => ({ default: module.MediaLibrary })));
const Account = lazy(() => import('./admin/Admin').then(module => ({ default: module.Account })));
function ScrollProgress(){const {scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:120,damping:30,mass:.2});return <motion.div className="scroll-progress" style={{scaleX}} aria-hidden="true"/>}
function PublicLayout({children}){const location=useLocation(),reducedMotion=useReducedMotion(),isResultsPage=location.pathname==='/results';return <div className={`public-site${isResultsPage?' public-site--results':''}`}><div className="site-atmosphere" aria-hidden="true"><i/><i/><i/></div><Helmet><title>FLAASH Digital | Digital Marketing & Creative Agency</title><meta name="description" content="FLAASH Digital combines strategy, creativity, performance marketing and technology to turn attention into measurable business growth."/></Helmet><ScrollProgress/><Navbar/><Chatbot/><motion.main key={location.pathname} initial={reducedMotion?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.5,ease:[.22,1,.36,1]}}>{children}</motion.main><Footer/></div>}
function LaunchScreen(){return <motion.div className="launch-screen" initial={{opacity:1}} exit={{opacity:0}} transition={{duration:.35,ease:'easeOut'}} aria-label="Loading FLAASH Digital" role="status"><motion.div className="launch-screen__content" initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:.38,ease:[.22,1,.36,1]}}><div className="launch-screen__logo"><img src="/flaash-logo.svg" alt="FLAASH Digital"/><i/></div><p>Digital solutions <b>•</b> Creative impact</p><span className="launch-screen__line"><i/></span></motion.div></motion.div>}
function NavigationLoader({destination}){const labels={'/':'Home','/about':'About','/services':'Services','/work':'Our Work','/results':'Results','/contact':'Contact'};const label=labels[destination]||'Service';return <div className="navigation-loading" role="status" aria-live="polite"><div><span>FLAASH</span><small>Loading {label}</small><i/></div></div>}
function App(){const location=useLocation();const navigate=useNavigate();const [launching,setLaunching]=useState(true);const [loadingDestination,setLoadingDestination]=useState('');const navigationTimer=useRef();const navigatingRef=useRef(false);useEffect(()=>{let favicon=document.querySelector("link[rel='icon']");if(!favicon){favicon=document.createElement('link');favicon.rel='icon';document.head.appendChild(favicon)}favicon.href='/favicon.svg';const hide=()=>setTimeout(()=>setLaunching(false),850);if(document.readyState==='complete')hide();else addEventListener('load',hide,{once:true});return()=>removeEventListener('load',hide);},[]);useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'auto'});setLoadingDestination('');navigatingRef.current=false;},[location.pathname]);useEffect(()=>{const handleInternalLink=(event)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey||navigatingRef.current)return;const anchor=event.target.closest('a[href]');if(!anchor||anchor.target||anchor.hasAttribute('download'))return;const href=anchor.getAttribute('href');if(!href||!href.startsWith('/')||href.startsWith('//'))return;const target=new URL(href,window.location.origin);if(target.pathname===location.pathname&&target.search===location.search)return;event.preventDefault();navigatingRef.current=true;setLoadingDestination(target.pathname);clearTimeout(navigationTimer.current);navigationTimer.current=setTimeout(()=>navigate(`${target.pathname}${target.search}${target.hash}`),430);};document.addEventListener('click',handleInternalLink,true);return()=>{document.removeEventListener('click',handleInternalLink,true);clearTimeout(navigationTimer.current);};},[location.pathname,location.search,navigate]);return <><AnimatePresence>{launching&&<LaunchScreen/>}{loadingDestination&&<NavigationLoader destination={loadingDestination}/>}</AnimatePresence><AnimatePresence mode="wait"><Suspense fallback={<div className="site-loading">Loading FLAASH…</div>}><Routes location={location} key={location.pathname}><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin" element={<AdminLayout/>}><Route index element={<Dashboard/>}/><Route path="leads" element={<Leads/>}/><Route path="media" element={<MediaLibrary/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="account" element={<Account/>}/><Route path=":type" element={<Collection/>}/><Route path=":type/new" element={<Editor/>}/><Route path=":type/:id/edit" element={<Editor/>}/></Route><Route path="*" element={<PublicRoutes/>}/></Routes></Suspense></AnimatePresence></>}
function PublicRoutes(){return <PublicLayout><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<ServiceDetail/>}/><Route path="/work" element={<Work/>}/><Route path="/work/:slug" element={<ProjectDetail/>}/><Route path="/results" element={<Results/>}/><Route path="/results/:slug" element={<CaseStudy/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy-policy" element={<Legal/>}/><Route path="/terms" element={<Legal terms/>}/><Route path="*" element={<NotFound/>}/></Routes></PublicLayout>};export default App;
