import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownRight, BarChart3, Check, ChevronLeft, ChevronRight, MoveUpRight, Play, Quote } from 'lucide-react';
import { services, clients, getProjectArtwork, getProjectWebsite, mergeProjects, mergeServices, projects, process, reasons, trimProjectImage } from '../data/content';
import { Button, Container, Eyebrow, Reveal, SectionHeading, ArrowLink } from '../components/UI';
import { Beam } from '../components/Brand';
import ImagePlaceholder from '../components/ImagePlaceholder';
import { getCollection } from '../services/api';
const rise = { hidden:{opacity:0,y:24}, visible:{opacity:1,y:0} };
const Sparkles = BarChart3;
function ServiceCard({ service }) { const Icon = service.Icon || Sparkles; return <article className="service-card"><Icon/><h3>{service.title || service.name}</h3><p>{service.shortDescription}</p><ArrowLink to={`/services/${service.slug}`}>Learn more</ArrowLink></article>; }
function ProjectCard({ project, index }) { const image=getProjectArtwork(project); const websiteUrl=getProjectWebsite(project); return <article className={`project-card project-card--${index % 3}`}><div className={`project-card__visual${image?' project-card__visual--image':''}`}>{image ? <img src={trimProjectImage(image)} alt={project.name} /> : <ImagePlaceholder label={`${project.name || project.title} project visual`} />}</div><div className="project-card__body"><p>{project.category || 'Featured work'}</p><h3>{project.name || project.title}</h3><span>{project.shortDescription}</span>{websiteUrl?<a href={websiteUrl} target="_blank" rel="noreferrer">Visit website <MoveUpRight size={15}/></a>:<ArrowLink to={`/work/${project.slug}`}>View project</ArrowLink>}</div></article>; }
function CaseStudyFeature({ item }) { const hasCover=Boolean(item?.coverImage?.url); return <section className="section case-study-feature"><Container><div className="case-study-feature__visual"><img className={hasCover?'':'case-study-feature__fallback-cover'} src={item?.coverImage?.url || '/images/featured-case-study-cover.png'} alt={item?.title || 'FLAASH digital growth case study'} /></div><div className="case-study-feature__copy"><Eyebrow>FEATURED CASE STUDY</Eyebrow><p className="case-study-feature__type">{item?.category || 'READY FOR YOUR NEXT SUCCESS STORY'}</p><h2>{item?.title || <>A focused brief.<br/>A <em>measurable</em> outcome.</>}</h2><div className="case-study-feature__steps"><article><b>Challenge</b><p>{item?.challenge || 'A dedicated space for the client challenge, approved before publication.'}</p></article><article><b>Strategy</b><p>{item?.strategy || 'The strategic response and delivery plan will be added here.'}</p></article><article><b>Results</b><p>{item?.results || 'Verified campaign outcomes appear only after client approval.'}</p></article></div>{item ? <Button to={`/results/${item.slug}`}>Read Case Study</Button> : <Button to="/contact">Create Your Success Story</Button>}</div></Container></section> }
function Testimonials({ items }) { const [active,setActive]=useState(0); if (!items.length) return null; const testimonial=items[active]; const previous=()=>setActive(x=>(x-1+items.length)%items.length), next=()=>setActive(x=>(x+1)%items.length); return <section className="section testimonials"><Container><SectionHeading centered eyebrow="CLIENT VOICES" title={<>Partnerships built on <em>clarity.</em></>}/><article className="testimonial"><Quote/><blockquote>“{testimonial.review}”</blockquote><div><b>{testimonial.clientName}</b><span>{[testimonial.designation,testimonial.company].filter(Boolean).join(', ')}</span></div><nav aria-label="Testimonial navigation"><button onClick={previous} aria-label="Previous testimonial"><ChevronLeft/></button><span>{String(active+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span><button onClick={next} aria-label="Next testimonial"><ChevronRight/></button></nav></article></Container></section>; }
export default function Home() { const [featured, setFeatured] = useState({ services, projects, caseStudy:null, testimonials:[] }); useEffect(() => { Promise.all([getCollection('services',{featured:true}),getCollection('projects',{featured:true}),getCollection('case-studies',{featured:true}),getCollection('testimonials',{featured:true})]).then(([s,p,c,t]) => setFeatured({services:mergeServices(s), projects:mergeProjects(p), caseStudy:c?.[0]||null, testimonials:t||[]})).catch(()=>{}); }, []); return <>
  <section className="hero"><Container className="hero__grid"><div className="hero__copy"><motion.div initial="hidden" animate="visible" transition={{staggerChildren:.08}}><motion.div variants={rise}><Eyebrow>INTEGRATED DIGITAL GROWTH PARTNER</Eyebrow></motion.div><motion.h1 variants={rise}>Built to make your brand <em>perform.</em></motion.h1><motion.p variants={rise}>Strategy, creative, performance marketing and digital products — connected by one senior team and measured against real business outcomes.</motion.p><motion.div variants={rise} className="hero__actions"><Button to="/contact">Discuss Your Project</Button><Button to="/work" variant="text">View Selected Work</Button></motion.div><motion.ul variants={rise}><li><Check/> Clear strategy</li><li><Check/> Senior execution</li><li><Check/> Measurable growth</li></motion.ul></motion.div></div><motion.aside className="hero__showcase" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.55,delay:.12}} aria-label="FLAASH capabilities"><div className="hero__showcase-top"><span>FLAASH / DIGITAL STUDIO</span><i>Available for selected projects</i></div><div className="hero__showcase-main"><small>From first click to lasting customer value</small><strong>Strategy<br/>that ships.</strong><p>We bring the thinking, design and delivery together — so momentum is never lost between partners.</p></div><div className="hero__showcase-grid"><article><span>01</span><b>Position</b><small>Brand & strategy</small></article><article><span>02</span><b>Acquire</b><small>Media & campaigns</small></article><article><span>03</span><b>Convert</b><small>Web & experiences</small></article></div><div className="hero__showcase-footer"><span>Strategy</span><span>Creative</span><span>Performance</span><span>Technology</span></div></motion.aside></Container></section>
  <section className="client-strip"><Container><p>Brands we’ve helped grow</p><div className="client-marquee"><div className="client-marquee__track">{[false,true].map(hidden=><div className="client-marquee__group" aria-hidden={hidden} key={String(hidden)}>{clients.map((client,i)=><span key={client}><i>{String(i+1).padStart(2,'0')}</i>{client}</span>)}</div>)}</div></div></Container></section>
  <section className="section intro"><Container className="intro__grid"><Reveal><Eyebrow>WHO WE ARE</Eyebrow><h2>We turn attention into <em>measurable</em> business growth.</h2></Reveal><Reveal delay={.15}><p>FLAASH Digital is a growth-focused agency that brings strategy, creativity, performance marketing and technology into one accountable team. We build the right work, then make it work harder.</p><a href="/about" className="text-link">Meet FLAASH <ArrowDownRight/></a></Reveal></Container></section>
  <section className="section services-preview"><Container><SectionHeading eyebrow="WHAT WE DO" title={<>Everything your brand needs <em>to grow.</em></>} copy="Strategy-led services that make the journey from first impression to genuine business impact feel connected."/><div className="services-grid">{featured.services.slice(0,8).map((x,i)=><Reveal key={x.slug} delay={i*.04}><ServiceCard service={x}/></Reveal>)}</div><div className="center-action"><Button to="/services" variant="outline">See all services</Button></div></Container></section>
  <section className="section process"><Container><SectionHeading eyebrow="HOW FLAASH WORKS" title={<>A clear route from signal <em>to scale.</em></>}/><div className="process__list">{process.map(([number,title,copy],i)=><Reveal key={number} delay={i*.06}><article><span>{number}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></Container></section>
  <section className="section work-preview"><Container><SectionHeading eyebrow="SELECTED WORK" title={<>Work that creates <em>impact.</em></>} copy="A selection of partnerships shaped around a useful idea, a focused strategy and better outcomes."/><div className="projects-grid">{featured.projects.slice(0,4).map((p,i)=><Reveal key={p.slug} delay={i*.07}><ProjectCard project={p} index={i}/></Reveal>)}</div><div className="center-action"><Button to="/work" variant="outline">Explore all work</Button></div></Container></section>
  <section className="section results-home"><Container className="results-home__grid"><div><SectionHeading dark eyebrow="RESULTS" title={<>Marketing that <em>moves numbers.</em></>} copy="Clear objectives, focused execution and transparent reporting. We connect every outcome to the strategy and work that produced it."/><Button to="/results" variant="light">Explore results</Button></div><div className="results-home__note"><span>01</span><h3>Real numbers, clearly explained.</h3><p>Every result is connected to the strategy behind it — never presented as an isolated vanity metric.</p><MoveUpRight/></div></Container></section>
  <CaseStudyFeature item={featured.caseStudy}/>
  <section className="section why"><Container><SectionHeading eyebrow="WHY FLAASH" title={<>Ambition deserves an <em>active partner.</em></>}/><div className="reasons-grid">{reasons.map(([title,copy],i)=><Reveal key={title} delay={i*.04}><article><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></Container></section>
  <Testimonials items={featured.testimonials}/>
  <section className="cta"><Container><div><Eyebrow dark>LET’S MAKE SOME NOISE</Eyebrow><h2>Ready to make your brand <em>impossible to ignore?</em></h2><p>Let’s build a digital strategy designed around your goals.</p><Button to="/contact">Start Your Project</Button><Button to="https://wa.me/919494582875" variant="light">WhatsApp Us</Button></div><div className="cta__bolt"><Play fill="currentColor"/><Beam/></div></Container></section>
</>; }
