import { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowDownRight, BarChart3, ChevronLeft, ChevronRight, MoveUpRight, Play, Quote, Sparkles } from 'lucide-react';
import { services, clients, getProjectArtwork, getProjectWebsite, mergeProjects, mergeServices, projects, process, reasons, trimProjectImage } from '../data/content';
import { Button, Container, Eyebrow, Reveal, SectionHeading, ArrowLink } from '../components/UI';
import { Beam } from '../components/Brand';
import ImagePlaceholder from '../components/ImagePlaceholder';
import { getCollection } from '../services/api';
const rise = { hidden:{opacity:0,y:24}, visible:{opacity:1,y:0} };
const impactStats = [{ value: 10, label: 'Clients served' }, { value: 100, label: 'Campaigns managed' }, { value: 5000, label: 'Leads generated' }, { value: 200, label: 'Creative projects' }, { value: 4, label: 'Years experience' }];
function CountUp({ value }) { const [count, setCount] = useState(0); const ref = useRef(null); useEffect(() => { const element = ref.current; if (!element) return; let frame; const observer = new IntersectionObserver(([entry]) => { if (!entry.isIntersecting) return; const start = performance.now(), duration = 2400; const animate = now => { const progress = Math.min((now - start) / duration, 1); const eased = 1 - Math.pow(1 - progress, 4); setCount(Math.round(value * eased)); if (progress < 1) frame = requestAnimationFrame(animate); }; frame = requestAnimationFrame(animate); observer.disconnect(); }, { threshold: .45 }); observer.observe(element); return () => { observer.disconnect(); cancelAnimationFrame(frame); }; }, [value]); return <span ref={ref}>{count.toLocaleString('en-IN')}+</span>; }
function ImpactStats() { return <Container className="stats stats--placeholders">{impactStats.map((stat, index) => <motion.div key={stat.label} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .4 }} transition={{ delay: index * .08, duration: .45 }}><CountUp value={stat.value}/><p>{stat.label}</p></motion.div>)}</Container>; }
function ServiceCard({ service }) { const Icon = service.Icon || Sparkles; return <article className="service-card"><Icon/><h3>{service.title || service.name}</h3><p>{service.shortDescription}</p><ArrowLink to={`/services/${service.slug}`}>Learn more</ArrowLink></article>; }
function ProjectCard({ project, index }) { const image=getProjectArtwork(project); const websiteUrl=getProjectWebsite(project); return <article className={`project-card project-card--${index % 3}`}><div className={`project-card__visual${image?' project-card__visual--image':''}`}>{image ? <img src={trimProjectImage(image)} alt={project.name} /> : <ImagePlaceholder label={`${project.name || project.title} project visual`} />}</div><div className="project-card__body"><p>{project.category || 'Featured work'}</p><h3>{project.name || project.title}</h3><span>{project.shortDescription}</span>{websiteUrl?<a href={websiteUrl} target="_blank" rel="noreferrer">Visit website <MoveUpRight size={15}/></a>:<ArrowLink to={`/work/${project.slug}`}>View project</ArrowLink>}</div></article>; }
function CaseStudyFeature({ item }) { const hasCover=Boolean(item?.coverImage?.url); return <section className="section case-study-feature"><Container><div className="case-study-feature__visual"><img className={hasCover?'':'case-study-feature__fallback-cover'} src={item?.coverImage?.url || '/images/featured-case-study-cover.png'} alt={item?.title || 'FLAASH digital growth case study'} /></div><div className="case-study-feature__copy"><Eyebrow>FEATURED CASE STUDY</Eyebrow><p className="case-study-feature__type">{item?.category || 'READY FOR YOUR NEXT SUCCESS STORY'}</p><h2>{item?.title || <>A focused brief.<br/>A <em>measurable</em> outcome.</>}</h2><div className="case-study-feature__steps"><article><b>Challenge</b><p>{item?.challenge || 'A dedicated space for the client challenge, approved before publication.'}</p></article><article><b>Strategy</b><p>{item?.strategy || 'The strategic response and delivery plan will be added here.'}</p></article><article><b>Results</b><p>{item?.results || 'Verified campaign outcomes appear only after client approval.'}</p></article></div>{item ? <Button to={`/results/${item.slug}`}>Read Case Study</Button> : <Button to="/contact">Create Your Success Story</Button>}</div></Container></section> }
function Testimonials({ items }) { const [active,setActive]=useState(0); if (!items.length) return <section className="section testimonials"><Container><SectionHeading centered eyebrow="CLIENT VOICES" title={<>Partnerships built on <em>clarity.</em></>}/><div className="testimonial-awaiting"><Quote/><h3>Client feedback belongs here — once it is approved.</h3><p>Testimonials are managed in the CMS and will be displayed with the client’s permission, company and role.</p></div></Container></section>; const testimonial=items[active]; const previous=()=>setActive(x=>(x-1+items.length)%items.length), next=()=>setActive(x=>(x+1)%items.length); return <section className="section testimonials"><Container><SectionHeading centered eyebrow="CLIENT VOICES" title={<>Partnerships built on <em>clarity.</em></>}/><article className="testimonial"><Quote/><blockquote>“{testimonial.review}”</blockquote><div><b>{testimonial.clientName}</b><span>{[testimonial.designation,testimonial.company].filter(Boolean).join(', ')}</span></div><nav aria-label="Testimonial navigation"><button onClick={previous} aria-label="Previous testimonial"><ChevronLeft/></button><span>{String(active+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span><button onClick={next} aria-label="Next testimonial"><ChevronRight/></button></nav></article></Container></section>; }
export default function Home() { const [featured, setFeatured] = useState({ services, projects, caseStudy:null, testimonials:[] }); useEffect(() => { Promise.all([getCollection('services',{featured:true}),getCollection('projects',{featured:true}),getCollection('case-studies',{featured:true}),getCollection('testimonials',{featured:true})]).then(([s,p,c,t]) => setFeatured({services:mergeServices(s), projects:mergeProjects(p), caseStudy:c?.[0]||null, testimonials:t||[]})).catch(()=>{}); }, []); return <>
  <section className="hero"><Container className="hero__grid"><div className="hero__copy"><motion.div initial="hidden" animate="visible" transition={{staggerChildren:.12}}><motion.div variants={rise}><Eyebrow>DIGITAL SOLUTIONS <b>•</b> CREATIVE IMPACT</Eyebrow></motion.div><motion.h1 variants={rise}>Powering brands.<br/><em>Driving growth.</em></motion.h1><motion.p variants={rise}>Result-driven digital marketing, branding and web solutions designed to help ambitious businesses grow, attract customers and create lasting digital impact.</motion.p><motion.div variants={rise} className="hero__actions"><Button to="/contact">Start Your Project</Button><Button to="/work" variant="text">Explore Our Work</Button></motion.div><motion.ul variants={rise}><li>Strategy</li><li>Creative</li><li>Performance</li><li>Technology</li></motion.ul></motion.div></div><motion.div className="hero__visual" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.9, delay:.25}}><div className="orbit orbit--one"/><div className="orbit orbit--two"/><div className="hero__sphere"><span>F</span><i/></div><div className="metric metric--top"><BarChart3/><span><b>Strategy</b>with momentum</span></div><div className="metric metric--bottom"><small>Growth signal</small><div><i/><i/><i/><i/><i/></div></div><div className="hero__line"/><Beam/></motion.div></Container></section>
  <section className="client-strip"><Container><p>Brands we’ve helped grow</p><div className="client-marquee"><div className="client-marquee__track">{[false,true].map(hidden=><div className="client-marquee__group" aria-hidden={hidden} key={String(hidden)}>{clients.map((client,i)=><span key={client}><i>{String(i+1).padStart(2,'0')}</i>{client}</span>)}</div>)}</div></div></Container></section>
  <section className="section intro"><Container className="intro__grid"><Reveal><Eyebrow>WHO WE ARE</Eyebrow><h2>We turn attention into <em>measurable</em> business growth.</h2></Reveal><Reveal delay={.15}><p>FLAASH Digital is a growth-focused agency that brings strategy, creativity, performance marketing and technology into one accountable team. We build the right work, then make it work harder.</p><a href="/about" className="text-link">Meet FLAASH <ArrowDownRight/></a></Reveal></Container><ImpactStats/></section>
  <section className="section services-preview"><Container><SectionHeading eyebrow="WHAT WE DO" title={<>Everything your brand needs <em>to grow.</em></>} copy="Strategy-led services that make the journey from first impression to genuine business impact feel connected."/><div className="services-grid">{featured.services.slice(0,8).map((x,i)=><Reveal key={x.slug} delay={i*.04}><ServiceCard service={x}/></Reveal>)}</div><div className="center-action"><Button to="/services" variant="outline">See all services</Button></div></Container></section>
  <section className="section process"><Container><SectionHeading eyebrow="HOW FLAASH WORKS" title={<>A clear route from signal <em>to scale.</em></>}/><div className="process__list">{process.map(([number,title,copy],i)=><Reveal key={number} delay={i*.06}><article><span>{number}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></Container></section>
  <section className="section work-preview"><Container><SectionHeading eyebrow="SELECTED WORK" title={<>Work that creates <em>impact.</em></>} copy="A selection of partnerships shaped around a useful idea, a focused strategy and better outcomes."/><div className="projects-grid">{featured.projects.slice(0,4).map((p,i)=><Reveal key={p.slug} delay={i*.07}><ProjectCard project={p} index={i}/></Reveal>)}</div><div className="center-action"><Button to="/work" variant="outline">Explore all work</Button></div></Container></section>
  <section className="section results-home"><Container className="results-home__grid"><div><SectionHeading dark eyebrow="RESULTS" title={<>Marketing that <em>moves numbers.</em></>} copy="We only publish confirmed campaign outcomes. Add approved case-study metrics in the CMS to share the full story."/><Button to="/results" variant="light">Explore results</Button></div><div className="results-home__note"><span>01</span><h3>Real numbers, clearly explained.</h3><p>Every result is connected to the strategy behind it — not presented as an isolated vanity metric.</p><MoveUpRight/></div></Container></section>
  <CaseStudyFeature item={featured.caseStudy}/>
  <section className="section why"><Container><SectionHeading eyebrow="WHY FLAASH" title={<>Ambition deserves an <em>active partner.</em></>}/><div className="reasons-grid">{reasons.map(([title,copy],i)=><Reveal key={title} delay={i*.04}><article><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article></Reveal>)}</div></Container></section>
  <Testimonials items={featured.testimonials}/>
  <section className="cta"><Container><div><Eyebrow dark>LET’S MAKE SOME NOISE</Eyebrow><h2>Ready to make your brand <em>impossible to ignore?</em></h2><p>Let’s build a digital strategy designed around your goals.</p><Button to="/contact">Start Your Project</Button><Button to="https://wa.me/" variant="light">WhatsApp Us</Button></div><div className="cta__bolt"><Play fill="currentColor"/><Beam/></div></Container></section>
</>; }
