import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Check, ChevronRight, Filter, Mail, Phone, Send, ShieldCheck, Sparkles } from 'lucide-react';
import { services as defaultServices, projects as defaultProjects, getProjectArtwork, getProjectWebsite, mergeProjects, mergeServices, trimProjectImage, process, reasons } from '../data/content';
import { getCollection, api } from '../services/api';
import { Button, Container, Eyebrow, Reveal, SectionHeading, EmptyState } from '../components/UI';
import ImagePlaceholder from '../components/ImagePlaceholder';
function Hero({ eyebrow, title, copy }) { return <section className="page-hero"><Container><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1>{copy&&<p>{copy}</p>}</Container></section>; }
const serviceEmojis = { 'meta-ads': '📣', 'google-ads': '🔎', seo: '📈', branding: '🎨', 'web-development': '💻', 'video-marketing': '🎬', 'lead-generation': '🎯' };
const serviceArtwork = {
  'social-media-marketing': '/images/social-media-marketing-hero.png',
  'meta-ads': '/images/meta-ads-hero.png',
  'google-ads': '/images/google-ads-hero.png',
  seo: '/images/seo-hero.png',
  branding: '/images/branding-hero.png',
  'web-development': '/images/web-development-hero.png',
  'lead-generation': '/images/lead-generation-hero.png',
  'video-marketing': '/images/video-marketing-hero.png',
};
function ServiceDetailHero({ item, title }) {
  const hasVideo = Boolean(item.heroVideoUrl);
  const artwork = serviceArtwork[item.slug];
  const emoji = serviceEmojis[item.slug] || '⚡';
  return <section className={`service-detail-hero service-detail-hero--${item.slug}`}><Container><div className="service-detail-hero__copy"><p className="breadcrumbs"><Link to="/services">Services</Link><ChevronRight size={14}/><span>{title}</span></p><Eyebrow>SERVICE</Eyebrow><h1>{title}</h1><p>{item.shortDescription}</p><Button to="/contact">Start a Project</Button></div><div className="service-detail-hero__visual">{hasVideo && !artwork ? <><video className="service-detail-hero__video" autoPlay muted loop playsInline preload="metadata" poster={item.heroImage?.url}><source src={item.heroVideoUrl} type="video/mp4"/></video><div className="service-detail-hero__visual-overlay"/></> : item.heroImage?.url ? <img src={item.heroImage.url} alt={`${title} service visual`}/> : artwork ? <img className="service-detail-hero__illustration" src={artwork} alt={`${title} service illustration`}/> : <div className="service-mark" aria-label={`${title} visual`}><span aria-hidden="true"><b>{emoji}</b></span><small>FLAASH DIGITAL</small><strong>{title}</strong><i/></div>}</div></Container></section>;
}
const serviceTitle = s => s.title || s.name;
function TeamSection(){const [members,setMembers]=useState([]);useEffect(()=>{getCollection('team').then(setMembers).catch(()=>{});},[]);return <section className="section team-section"><Container><SectionHeading eyebrow="THE TEAM" title={<>Good work needs good <em>people.</em></>} copy="Meet the people behind the strategy, creative and day-to-day momentum."/>{members.length?<div className="team-grid">{members.map(member=><article key={member._id}><div>{member.photo?.url?<img src={member.photo.url} alt={member.name}/>:<ImagePlaceholder label={`${member.name} portrait`} aspect="portrait"/>}</div><h3>{member.name}</h3><p>{member.designation}</p></article>)}</div>:<div className="team-awaiting"><div className="team-awaiting__image"><img src="/images/team-collaboration-cover.png" alt="FLAASH team collaborating on digital strategy"/></div><div><h3>A home for the people behind FLAASH.</h3><p>Add active team members in Admin to publish their photograph, role, biography and social links here.</p></div></div>}</Container></section>}
export function About() { return <><Hero eyebrow="ABOUT FLAASH" title={<>Creative thinking.<br/><em>Performance mindset.</em></>} copy="A modern agency for teams that want more than marketing activity — they want purposeful forward movement."/><section className="section"><Container className="split"><div><Eyebrow>OUR STORY</Eyebrow><h2>Built for the work that <em>creates momentum.</em></h2></div><div><p>FLAASH exists to help ambitious businesses make better use of digital opportunity. We pair creative instinct with performance discipline, so each idea has a reason, a direction and a way to be measured.</p><p>We work openly, move with intent and care about the practical outcome as much as the visual one.</p></div></Container></section><section className="dark-panel"><Container className="mission"><article><Eyebrow dark>MISSION</Eyebrow><h2>To help ambitious brands turn digital opportunities into measurable business growth.</h2></article><article><Eyebrow dark>VISION</Eyebrow><h2>To build brands that don’t simply exist online, but stand out, connect and grow.</h2></article></Container></section><section className="section"><Container><SectionHeading eyebrow="OUR VALUES" title="The standards we bring to every partnership."/><div className="reasons-grid">{reasons.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></Container></section><Process/><TeamSection/></>; }
export function Process() { return <section className="section process"><Container><SectionHeading eyebrow="OUR PROCESS" title={<>A method designed for <em>forward motion.</em></>}/><div className="process__list">{process.map(([n,t,c])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></Container></section>; }
export function Services() { const [items,setItems]=useState(defaultServices); useEffect(()=>{getCollection('services').then(x=>setItems(mergeServices(x))).catch(()=>{});},[]); return <><Hero eyebrow="SERVICES" title={<>Digital solutions built <em>for growth.</em></>} copy="One strategic team for the creative, marketing and technology work that brings your brand closer to its goals."/><section className="section"><Container><div className="services-list">{items.map((s,i)=>{const Icon=s.Icon||Sparkles;return <Reveal key={s.slug} delay={i*.04}><Link to={`/services/${s.slug}`} className="service-row"><span>0{i+1}</span><Icon/><div><h2>{serviceTitle(s)}</h2><p>{s.shortDescription}</p></div><ChevronRight/></Link></Reveal>})}</div></Container></section></>; }
export function ServiceDetail() { const {slug}=useParams(); const [item,setItem]=useState(defaultServices.find(s=>s.slug===slug)); useEffect(()=>{getCollection(`services/${slug}`).then(setItem).catch(()=>{});},[slug]); if(!item) return <NotFound/>; const title=serviceTitle(item); return <><ServiceDetailHero item={item} title={title}/><section className="section"><Container className="detail-grid"><aside><b>Overview</b><a href="#benefits">Benefits</a><a href="#deliverables">Deliverables</a><a href="#process">Process</a></aside><main><h2>A practical service built around your business.</h2><p>{item.description || 'We shape this service around the challenges that matter to your team, bringing a clear plan, thoughtful execution and useful reporting together.'}</p><h3 id="benefits">What it helps solve</h3><ul className="check-list">{(item.benefits?.length?item.benefits:['Unclear customer journeys','Inconsistent creative output','Marketing activity without a measurable direction']).map(x=><li key={x}><Check/>{x}</li>)}</ul><h3 id="deliverables">What we deliver</h3><ul className="check-list">{(item.deliverables?.length?item.deliverables:['A tailored strategy','Purposeful creative and execution','Clear performance reporting']).map(x=><li key={x}><Check/>{x}</li>)}</ul><Button to="/contact">Discuss this service</Button></main></Container></section><Process /></>; }
function Project({project,index=0}) { const image=getProjectArtwork(project); const websiteUrl=getProjectWebsite(project); return <article className="project-card"><div className={`project-card__visual${image?' project-card__visual--image':''}`}>{image?<img src={trimProjectImage(image)} alt={project.name || project.title}/>:<span>{String(index+1).padStart(2,'0')}</span>}</div><div className="project-card__body"><p>{project.category}</p><h2>{project.name || project.title}</h2><span>{project.shortDescription}</span>{websiteUrl?<a href={websiteUrl} target="_blank" rel="noreferrer">Visit website <ChevronRight size={17}/></a>:<Link to={`/work/${project.slug}`}>View project <ChevronRight size={17}/></Link>}</div></article>; }
export function Work() { const [items,setItems]=useState(defaultProjects); const [filter,setFilter]=useState('All'); useEffect(()=>{getCollection('projects').then(x=>setItems(mergeProjects(x))).catch(()=>{});},[]); const cats=['All',...new Set(items.map(x=>x.category).filter(Boolean))]; const list=filter==='All'?items:items.filter(x=>x.category===filter); return <><Hero eyebrow="OUR WORK" title={<>Ideas brought <em>to life.</em></>} copy="Selected work from partnerships built on clarity, craft and an appetite for better results."/><section className="section"><Container><div className="filters" aria-label="Filter work"><Filter size={17}/>{cats.map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="projects-grid">{list.map((x,i)=><Project key={x.slug} project={x} index={i}/>)}</div></Container></section></>; }
export function ProjectDetail() { const {slug}=useParams(); const fallback=defaultProjects.find(x=>x.slug===slug); const [item,setItem]=useState(fallback); useEffect(()=>{getCollection(`projects/${slug}`).then(setItem).catch(()=>{});},[slug]); if(!item)return <NotFound/>; return <><Hero eyebrow={item.category||'PROJECT'} title={item.name||item.title} copy={item.shortDescription}/><section className="section"><Container className="detail-grid"><aside><b>{item.client}</b><span>{item.industry||'Featured partnership'}</span></aside><main><h2>The brief</h2><p>{item.challenge||'The detailed project narrative is being prepared by the FLAASH team.'}</p><h3>Our approach</h3><p>{item.strategy||'A focused programme of strategy, creative production and performance optimisation.'}</p><h3>Outcome</h3><p>{item.results||'Approved results and campaign metrics will be published here.'}</p><Button to="/contact">Create your project</Button></main></Container></section></>; }
export function Results() { const [items,setItems]=useState([]); useEffect(()=>{getCollection('case-studies').then(setItems).catch(()=>{});},[]); return <><Hero eyebrow="CASE STUDIES" title={<>Results speak louder <em>than promises.</em></>} copy="The stories, strategies and approved results behind our client work."/><section className="section results-page"><Container>{items.length?<div className="case-grid">{items.map(x=><article key={x.slug} className="case-card"><span>{x.category}</span><h2>{x.title}</h2><p>{x.challenge}</p><Link to={`/results/${x.slug}`}>Read case study <ChevronRight size={17}/></Link></article>)}</div>:<EmptyState>Case studies will appear here once verified client results are published.</EmptyState>}</Container></section></>; }
export function CaseStudy() { const {slug}=useParams(); const [item,setItem]=useState(null); useEffect(()=>{getCollection(`case-studies/${slug}`).then(setItem).catch(()=>{});},[slug]); if(!item)return <NotFound/>; return <><Hero eyebrow="CASE STUDY" title={item.title} copy={item.client}/><section className="section"><Container className="detail-grid"><aside><b>{item.category}</b></aside><main><h2>Challenge</h2><p>{item.challenge}</p><h3>Strategy</h3><p>{item.strategy}</p><h3>Results</h3><p>{item.results}</p></main></Container></section></>; }
export function Contact() {
  const [state,setState]=useState('idle');
  const [errorMessage,setErrorMessage]=useState('');
  const [settings,setSettings]=useState({phone:'+91 94945 82875',email:'flaashdigital@gmail.com'});
  useEffect(()=>{api.get('/settings').then(response=>setSettings(current=>({...current,...(response.data.data||{})}))).catch(()=>{});},[]);
  const submit=async e=>{e.preventDefault();const formElement=e.currentTarget;const form=Object.fromEntries(new FormData(formElement));if(form.website)return;setState('sending');setErrorMessage('');try{await api.post('/contact',form);setState('sent');formElement.reset()}catch(error){setState('error');setErrorMessage(error.response?.data?.message||error.message||'Unable to send your inquiry. Please try again.')}};
  const phoneHref=`tel:${String(settings.phone||'').replace(/[^\d+]/g,'')}`;
  return <><Hero eyebrow="CONTACT" title={<>Let’s build something <em>that grows.</em></>} copy="Tell us where you want to go. We’ll start by understanding the opportunity."/><section className="section"><Container className="contact-grid"><div className="contact-details"><Eyebrow>GET IN TOUCH</Eyebrow><h2>A conversation is a good place to start.</h2><p>Reach our team directly, or send an enquiry using the form.</p><p><Mail/><a href={`mailto:${settings.email}`}>{settings.email}</a></p><p><Phone/><a href={phoneHref}>{settings.phone}</a></p></div><form className="contact-form" onSubmit={submit}><label>Name *<input name="name" required maxLength="100"/></label><label>Company<input name="company" maxLength="120"/></label><label>Email *<input name="email" type="email" required/></label><label>Phone *<input name="phone" required/></label><label>Service interested in<select name="service"><option value="">Select a service</option>{defaultServices.map(x=><option key={x.slug}>{x.title}</option>)}</select></label><label>Approximate budget<select name="budget"><option>Not Sure</option><option>₹25K–₹50K</option><option>₹50K–₹1L</option><option>₹1L–₹3L</option><option>₹3L+</option></select></label><label className="full">Message *<textarea name="message" required rows="5"/></label><input name="website" className="honeypot" tabIndex="-1" autoComplete="off"/><label className="consent full"><input type="checkbox" required/> I agree to be contacted regarding my inquiry.</label><Button type="submit" disabled={state==='sending'}>{state==='sent'?'Inquiry sent':state==='sending'?'Sending…':'Send Inquiry'}</Button>{state==='error'&&<p className="form-error">{errorMessage}</p>}</form></Container></section></>; }
export function Legal({terms=false}) { return <><Hero eyebrow="FLAASH DIGITAL" title={terms?'Terms & Conditions':'Privacy Policy'} copy="A clear placeholder ready for final legal review before launch."/><section className="section legal"><Container><h2>Review required before publication</h2><p>This page is intentionally a professional placeholder. FLAASH Digital should add its approved legal copy, governing jurisdiction and contact details before the live website is published.</p><h3>Information we collect</h3><p>Contact inquiries submitted through this site are used only to respond to the inquiry and manage an appropriate business relationship.</p></Container></section></>; }
export function NotFound() { return <section className="not-found"><Container><span>404</span><h1>Looks like this page lost its <em>signal.</em></h1><Button to="/">Back to Home</Button></Container></section>; }
