import { useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Outlet, useLocation, useNavigate, useParams } from 'react-router-dom';
import { BarChart3, BriefcaseBusiness, ClipboardList, Copy, FileText, Image, LayoutDashboard, LogOut, Menu, MessageSquare, Settings, Sparkles, Trash2, Upload, UserCircle, Users, X } from 'lucide-react';
import { api } from '../services/api';
import { Brand } from '../components/Brand';
import { Button, EmptyState } from '../components/UI';
import { projects as websiteProjects, services as defaultServices } from '../data/content';
const nav=[['/admin',LayoutDashboard,'Dashboard'],['/admin/services',Sparkles,'Services'],['/admin/projects',BriefcaseBusiness,'Portfolio'],['/admin/case-studies',BarChart3,'Case Studies'],['/admin/testimonials',MessageSquare,'Testimonials'],['/admin/clients',Users,'Clients'],['/admin/team',Users,'Team'],['/admin/leads',ClipboardList,'Contact Leads'],['/admin/media',Image,'Media Library'],['/admin/settings',Settings,'Site Settings'],['/admin/account',UserCircle,'Account']];
const galleryFields=Array.from({length:6},(_,index)=>`galleryImage${index+1}Url`);
const imageFieldDetails={thumbnailUrl:{label:'Card / listing image',help:'Used on portfolio and service cards.'},heroImageUrl:{label:'Hero / main banner image',help:'Used at the top of the detail page when no video is selected.'},coverImageUrl:{label:'Case study cover image',help:'Used as the main case-study visual.'},photoUrl:{label:'Portrait image',help:'Used for the testimonial or team profile.'},companyLogoUrl:{label:'Company logo',help:'Used beside the testimonial.'},logoUrl:{label:'Client logo',help:'Used in client brand areas.'},...Object.fromEntries(galleryFields.map((field,index)=>[field,{label:`Gallery image ${index+1}`,help:`Gallery position ${index+1}. Leave empty when this position is not needed.`}]))};
const collectionConfig={services:{label:'Services',singular:'Service',fields:['title','shortDescription','description','status','isFeatured','displayOrder']},projects:{label:'Portfolio projects',singular:'Project',fields:['name','client','category','shortDescription','description','challenge','strategy','results','status','isFeatured','displayOrder']},'case-studies':{label:'Case studies',singular:'Case study',fields:['title','client','category','challenge','strategy','results','status','isFeatured','displayOrder']},testimonials:{label:'Testimonials',singular:'Testimonial',fields:['clientName','company','designation','review','rating','status','isFeatured','displayOrder']},clients:{label:'Clients',singular:'Client',fields:['name','industry','website','isFeatured','displayOrder']},team:{label:'Team members',singular:'Team member',fields:['name','designation','bio','linkedin','instagram','status','displayOrder']}};
export function EnhancedCollection(){
  const {type}=useParams();
  const config=collectionConfig[type];
  const [items,setItems]=useState(null);
  const [selected,setSelected]=useState([]);
  const [busy,setBusy]=useState(false);
  useEffect(()=>{if(!config)return;setItems(null);setSelected([]);const load=async()=>{try{let response=await api.get(`/admin/${type}`);let records=response.data.data.items||response.data.data;if(type==='services'){const savedSlugs=new Set(records.map(item=>item.slug));const missing=defaultServices.filter(service=>!savedSlugs.has(service.slug));if(missing.length){await Promise.all(missing.map((service,index)=>api.post('/admin/services',{slug:service.slug,title:service.title,shortDescription:service.shortDescription,status:'published',isFeatured:true,displayOrder:index+1})));response=await api.get('/admin/services');records=response.data.data.items||response.data.data;}}setItems(records);}catch{setItems([]);}};load();},[type]);
  if(!config)return <Navigate to="/admin"/>;
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(current=>current.length===items.length?[]:items.map(item=>item._id));
  const deleteSelected=async()=>{if(!selected.length||!confirm(`Delete ${selected.length} selected ${config.label.toLowerCase()}? This cannot be undone.`))return;setBusy(true);try{await Promise.all(selected.map(id=>api.delete(`/admin/${type}/${id}`)));setItems(current=>current.filter(item=>!selected.includes(item._id)));setSelected([]);}finally{setBusy(false);}};
  return <section className="admin-page"><div className="admin-title"><div><p>CONTENT MANAGEMENT</p><h1>{config.label}</h1></div><Link className="admin-button" to={`/admin/${type}/new`}>Add {config.singular}</Link></div>{items===null?<div className="admin-panel">Loading content...</div>:items.length?<><div className="admin-selection-bar"><span>{selected.length?`${selected.length} selected`:'Select items to delete'}</span><button type="button" className="danger" disabled={!selected.length||busy} onClick={deleteSelected}><Trash2 size={15}/>{busy?'Deleting...':'Delete selected'}</button></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all" checked={selected.length===items.length} onChange={toggleAll}/></th><th>Name</th><th>Status</th><th>Featured</th><th>Order</th><th/></tr></thead><tbody>{items.map(x=><tr key={x._id}><td><input type="checkbox" aria-label={`Select ${x.title||x.name||x.clientName}`} checked={selected.includes(x._id)} onChange={()=>toggle(x._id)}/></td><td><b>{x.title||x.name||x.clientName}</b><small>{x.slug||x.company||'-'}</small></td><td><span className={`status status--${x.status||'published'}`}>{x.status||'published'}</span></td><td>{x.isFeatured?'Yes':'-'}</td><td>{x.displayOrder??'-'}</td><td><Link to={`/admin/${type}/${x._id}/edit`}>Edit</Link></td></tr>)}</tbody></table></div></>:<EmptyState>No {config.label.toLowerCase()} yet. Start by creating one.</EmptyState>}</section>;
}
function ServiceEditor(){
  const {id}=useParams();
  const navigate=useNavigate();
  const [item,setItem]=useState({status:'published',displayOrder:0,isFeatured:true});
  const [file,setFile]=useState(null);
  const [preview,setPreview]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{if(id)api.get(`/admin/services/${id}`).then(response=>setItem(response.data.data)).catch(()=>setError('Unable to load this service.'));},[id]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const values=Object.fromEntries(new FormData(event.currentTarget));values.isFeatured=values.isFeatured==='on';values.displayOrder=Number(values.displayOrder||0);let imageUrl=item.heroImage?.url||'';if(file){const uploadData=new FormData();uploadData.append('image',file);uploadData.append('folder','services');uploadData.append('alt',values.title||'FLAASH service image');const response=await api.post('/admin/upload',uploadData);imageUrl=response.data.data.url;}if(!imageUrl){setError('Please choose a service image before saving.');return;}values.heroImageUrl=imageUrl;values.thumbnailUrl=imageUrl;if(id)await api.patch(`/admin/services/${id}`,values);else await api.post('/admin/services',values);navigate('/admin/services');}catch(requestError){setError(requestError.response?.data?.message||'Unable to upload and save this service. Please try again.');}finally{setBusy(false);}};
  const del=async()=>{if(confirm('Delete this service? This cannot be undone.')){await api.delete(`/admin/services/${id}`);navigate('/admin/services');}};
  const imageSrc=preview||item.heroImage?.url||'';
  return <section className="admin-page"><div className="admin-title"><div><p>CONTENT MANAGEMENT</p><h1>{id?'Edit':'New'} Service</h1></div><Link to="/admin/services">Cancel</Link></div><p className="editor-help">Add the service name, a short description and one main image. The image will appear automatically on the service page.</p><form key={item._id||'new'} className="editor-form" onSubmit={submit}><label>Service name<input name="title" defaultValue={item.title||''} required placeholder="Example: SEO"/></label><label>Display order<input name="displayOrder" type="number" min="0" defaultValue={item.displayOrder??0}/></label><label className="wide">Short description<textarea name="shortDescription" defaultValue={item.shortDescription||''} rows="3" required placeholder="A clear one-line benefit for visitors."/></label><label className="wide">Full description (optional)<textarea name="description" defaultValue={item.description||''} rows="5" placeholder="Explain what this service includes."/></label><label className="wide service-image-upload">Main service image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>setFile(event.target.files?.[0]||null)}/><small>JPEG, PNG, WebP or AVIF, maximum 5 MB.</small>{imageSrc&&<img src={imageSrc} alt="Selected service preview"/>}</label><label>Status<select name="status" defaultValue={item.status||'published'}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="toggle"><input type="checkbox" name="isFeatured" defaultChecked={item.isFeatured!==false}/><span/>Feature on homepage</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><Button type="submit" disabled={busy}>{busy?(file?'Uploading image...':'Saving...'):'Save service'}</Button>{id&&<button type="button" className="danger" onClick={del}>Delete service</button>}</div></form></section>;
}
function ProjectEditor(){
  const {id}=useParams();
  const navigate=useNavigate();
  const [item,setItem]=useState({status:'published',isFeatured:true});
  const [file,setFile]=useState(null);
  const [preview,setPreview]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{if(id)api.get(`/admin/projects/${id}`).then(response=>setItem(response.data.data)).catch(()=>setError('Unable to load this project.'));},[id]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const values=Object.fromEntries(new FormData(event.currentTarget));values.isFeatured=values.isFeatured==='on';let imageUrl=item.thumbnail?.url||item.heroImage?.url||'';if(file){const uploadData=new FormData();uploadData.append('image',file);uploadData.append('folder','projects');uploadData.append('alt',values.name||'FLAASH portfolio project');const response=await api.post('/admin/upload',uploadData);imageUrl=response.data.data.url;}if(!imageUrl){setError('Please choose a project image before saving.');return;}values.thumbnailUrl=imageUrl;values.heroImageUrl=imageUrl;if(id)await api.patch(`/admin/projects/${id}`,values);else await api.post('/admin/projects',values);navigate('/admin/projects');}catch(requestError){setError(requestError.response?.data?.message||'Unable to upload and save this project. Please try again.');}finally{setBusy(false);}};
  const del=async()=>{if(confirm('Delete this project? This cannot be undone.')){await api.delete(`/admin/projects/${id}`);navigate('/admin/projects');}};
  const imageSrc=preview||item.thumbnail?.url||item.heroImage?.url||'';
  return <section className="admin-page"><div className="admin-title"><div><p>PORTFOLIO MANAGEMENT</p><h1>{id?'Edit':'New'} Project</h1></div><Link to="/admin/projects">Cancel</Link></div><p className="editor-help">Add only the important project details and one main image. The image will appear automatically in your portfolio.</p><form key={item._id||'new'} className="editor-form" onSubmit={submit}><label>Project name<input name="name" defaultValue={item.name||''} required placeholder="Example: Indian Cricket Academy"/></label><label>Client name<input name="client" defaultValue={item.client||''} placeholder="Client or brand name"/></label><label className="wide">Website URL (optional)<input name="websiteUrl" type="url" defaultValue={item.websiteUrl||''} placeholder="https://example.com"/><small>Visitors will see a “Visit website” link on this portfolio card.</small></label><label>Category<select name="category" defaultValue={item.category||'Lead Generation'}><option>Lead Generation</option><option>Branding</option><option>Social Media</option><option>Web Development</option><option>Digital Marketing</option><option>Other</option></select></label><label>Status<select name="status" defaultValue={item.status||'published'}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="wide">Short summary<textarea name="shortDescription" defaultValue={item.shortDescription||''} rows="3" required placeholder="A short description shown on the project card."/></label><label className="wide">Project details (optional)<textarea name="description" defaultValue={item.description||''} rows="5" placeholder="Add a short description of the work completed."/></label><label className="wide service-image-upload">Main portfolio image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>setFile(event.target.files?.[0]||null)}/><small>JPEG, PNG, WebP or AVIF, maximum 5 MB.</small>{imageSrc&&<img src={imageSrc} alt="Selected project preview"/>}</label><label className="toggle"><input type="checkbox" name="isFeatured" defaultChecked={item.isFeatured!==false}/><span/>Show on homepage</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><Button type="submit" disabled={busy}>{busy?(file?'Uploading image...':'Saving...'):'Save project'}</Button>{id&&<button type="button" className="danger" onClick={del}>Delete project</button>}</div></form></section>;
}
function CaseStudyEditor(){
  const {id}=useParams();
  const navigate=useNavigate();
  const [item,setItem]=useState({status:'published',isFeatured:true});
  const [file,setFile]=useState(null);
  const [preview,setPreview]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{if(id)api.get(`/admin/case-studies/${id}`).then(response=>setItem(response.data.data)).catch(()=>setError('Unable to load this case study.'));},[id]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const values=Object.fromEntries(new FormData(event.currentTarget));values.isFeatured=values.isFeatured==='on';let imageUrl=item.coverImage?.url||'';if(file){const uploadData=new FormData();uploadData.append('image',file);uploadData.append('folder','case-studies');uploadData.append('alt',values.title||'FLAASH case study');const response=await api.post('/admin/upload',uploadData);imageUrl=response.data.data.url;}if(!imageUrl){setError('Please choose a case study image before saving.');return;}values.coverImageUrl=imageUrl;if(id)await api.patch(`/admin/case-studies/${id}`,values);else await api.post('/admin/case-studies',values);navigate('/admin/case-studies');}catch(requestError){setError(requestError.response?.data?.message||'Unable to upload and save this case study. Please try again.');}finally{setBusy(false);}};
  const del=async()=>{if(confirm('Delete this case study? This cannot be undone.')){await api.delete(`/admin/case-studies/${id}`);navigate('/admin/case-studies');}};
  const imageSrc=preview||item.coverImage?.url||'';
  return <section className="admin-page"><div className="admin-title"><div><p>RESULTS MANAGEMENT</p><h1>{id?'Edit':'New'} Case Study</h1></div><Link to="/admin/case-studies">Cancel</Link></div><p className="editor-help">Use a clear title, the main result story and one cover image. This image appears automatically on the website.</p><form key={item._id||'new'} className="editor-form" onSubmit={submit}><label>Case study title<input name="title" defaultValue={item.title||''} required placeholder="Example: Growth campaign for ABC"/></label><label>Client name<input name="client" defaultValue={item.client||''} placeholder="Client or brand name"/></label><label>Category<select name="category" defaultValue={item.category||'Digital Marketing'}><option>Digital Marketing</option><option>Lead Generation</option><option>Branding</option><option>Social Media</option><option>Web Development</option><option>Other</option></select></label><label>Status<select name="status" defaultValue={item.status||'published'}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="wide">Challenge<textarea name="challenge" defaultValue={item.challenge||''} rows="3" required placeholder="What was the main client challenge?"/></label><label className="wide">Strategy<textarea name="strategy" defaultValue={item.strategy||''} rows="3" required placeholder="What did FLAASH do?"/></label><label className="wide">Results<textarea name="results" defaultValue={item.results||''} rows="3" required placeholder="What outcome was achieved?"/></label><label className="wide service-image-upload">Case study cover image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>setFile(event.target.files?.[0]||null)}/><small>JPEG, PNG, WebP or AVIF, maximum 5 MB.</small>{imageSrc&&<img src={imageSrc} alt="Selected case study preview"/>}</label><label className="toggle"><input type="checkbox" name="isFeatured" defaultChecked={item.isFeatured!==false}/><span/>Feature on homepage</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><Button type="submit" disabled={busy}>{busy?(file?'Uploading image...':'Saving...'):'Save case study'}</Button>{id&&<button type="button" className="danger" onClick={del}>Delete case study</button>}</div></form></section>;
}
function TestimonialEditor(){
  const {id}=useParams();
  const navigate=useNavigate();
  const [item,setItem]=useState({status:'published',isFeatured:true,rating:5});
  const [file,setFile]=useState(null);
  const [preview,setPreview]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  useEffect(()=>{if(id)api.get(`/admin/testimonials/${id}`).then(response=>setItem(response.data.data)).catch(()=>setError('Unable to load this testimonial.'));},[id]);
  useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
  const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const values=Object.fromEntries(new FormData(event.currentTarget));values.isFeatured=values.isFeatured==='on';let imageUrl=item.photo?.url||'';if(file){const uploadData=new FormData();uploadData.append('image',file);uploadData.append('folder','testimonials');uploadData.append('alt',values.clientName||'FLAASH client');const response=await api.post('/admin/upload',uploadData);imageUrl=response.data.data.url;}if(!imageUrl){setError('Please choose a client photo before saving.');return;}values.photoUrl=imageUrl;if(id)await api.patch(`/admin/testimonials/${id}`,values);else await api.post('/admin/testimonials',values);navigate('/admin/testimonials');}catch(requestError){setError(requestError.response?.data?.message||'Unable to upload and save this testimonial. Please try again.');}finally{setBusy(false);}};
  const del=async()=>{if(confirm('Delete this testimonial? This cannot be undone.')){await api.delete(`/admin/testimonials/${id}`);navigate('/admin/testimonials');}};
  const imageSrc=preview||item.photo?.url||'';
  return <section className="admin-page"><div className="admin-title"><div><p>CLIENT VOICES</p><h1>{id?'Edit':'New'} Testimonial</h1></div><Link to="/admin/testimonials">Cancel</Link></div><p className="editor-help">Add the client name, their feedback and one photo. It will be shown automatically in the testimonial section.</p><form key={item._id||'new'} className="editor-form" onSubmit={submit}><label>Client name<input name="clientName" defaultValue={item.clientName||''} required placeholder="Client's full name"/></label><label>Company<input name="company" defaultValue={item.company||''} placeholder="Company name"/></label><label>Role or designation<input name="designation" defaultValue={item.designation||''} placeholder="Example: Founder"/></label><label>Rating<select name="rating" defaultValue={item.rating||5}><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select></label><label className="wide">Client feedback<textarea name="review" defaultValue={item.review||''} rows="5" required placeholder="Add the client's approved testimonial."/></label><label className="wide service-image-upload">Client photo<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>setFile(event.target.files?.[0]||null)}/><small>JPEG, PNG, WebP or AVIF, maximum 5 MB.</small>{imageSrc&&<img src={imageSrc} alt="Selected client preview"/>}</label><label>Status<select name="status" defaultValue={item.status||'published'}><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></label><label className="toggle"><input type="checkbox" name="isFeatured" defaultChecked={item.isFeatured!==false}/><span/>Show on homepage</label>{error&&<p className="form-error">{error}</p>}<div className="editor-actions"><Button type="submit" disabled={busy}>{busy?(file?'Uploading image...':'Saving...'):'Save testimonial'}</Button>{id&&<button type="button" className="danger" onClick={del}>Delete testimonial</button>}</div></form></section>;
}
export function ContentEditor(){const {type}=useParams();if(type==='services')return <ServiceEditor/>;if(type==='projects')return <ProjectEditor/>;if(type==='case-studies')return <CaseStudyEditor/>;if(type==='testimonials')return <TestimonialEditor/>;return <Editor/>;}
function useAuth(){const [user,setUser]=useState(undefined);useEffect(()=>{api.get('/auth/me').then(r=>setUser(r.data.data)).catch(()=>setUser(null));},[]);return user}
export function AdminLayout(){const user=useAuth(),[open,setOpen]=useState(false),navigate=useNavigate();if(user===undefined)return <div className="admin-loading">Loading admin…</div>;if(!user)return <Navigate to="/admin/login" replace/>;const logout=async()=>{await api.post('/auth/logout');navigate('/admin/login')};return <div className="admin"><aside className={open?'is-open':''}><div><Brand dark/><button className="admin-close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([to,Icon,label])=><NavLink key={to} end={to==='/admin'} to={to} onClick={()=>setOpen(false)}><Icon size={18}/>{label}</NavLink>)}</nav><button onClick={logout}><LogOut size={18}/>Logout</button></aside><main><header><button className="admin-menu" onClick={()=>setOpen(true)}><Menu/></button><div><b>{user.name}</b><span>{user.role}</span></div></header><Outlet/></main></div>}
export function AdminLogin(){const [error,setError]=useState(''),navigate=useNavigate();const submit=async e=>{e.preventDefault();try{await api.post('/auth/login',Object.fromEntries(new FormData(e.currentTarget)));navigate('/admin')}catch(e){setError(e.response?.data?.message||'Unable to sign in.')}};return <main className="admin-login"><div><Brand/><p>Admin workspace</p><h1>Welcome back.</h1><form onSubmit={submit}><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label>{error&&<p className="form-error">{error}</p>}<Button type="submit">Sign in</Button></form><Link to="/">← Return to website</Link></div></main>}
export function Dashboard(){const [summary,setSummary]=useState(null);useEffect(()=>{api.get('/admin/dashboard').then(r=>setSummary(r.data.data)).catch(()=>setSummary({}));},[]);const cards=[['Services',summary?.services],['Portfolio projects',summary?.projects],['Case studies',summary?.caseStudies],['New leads',summary?.newLeads]];return <section className="admin-page"><div className="admin-title"><div><p>OVERVIEW</p><h1>Dashboard</h1></div><Link className="admin-button" to="/admin/projects/new">Add project</Link></div><div className="admin-stats">{cards.map(([label,value])=><article key={label}><p>{label}</p><strong>{summary?value??0:'—'}</strong></article>)}</div><div className="admin-panel"><h2>Recent activity</h2><p>Recent inquiries and content updates will appear here as your team starts using the CMS.</p></div></section>}
const pluralize=k=>k==='team'?'team':k;
export function Collection(){const {type}=useParams();const config=collectionConfig[type];const [items,setItems]=useState(null);useEffect(()=>{if(config)api.get(`/admin/${type}`).then(r=>setItems(r.data.data.items||r.data.data)).catch(()=>setItems([]));},[type,config]);if(!config)return <Navigate to="/admin"/>;return <section className="admin-page"><div className="admin-title"><div><p>CONTENT MANAGEMENT</p><h1>{config.label}</h1></div><Link className="admin-button" to={`/admin/${type}/new`}>Add {config.singular}</Link></div>{items===null?<div className="admin-panel">Loading content…</div>:items.length?<div className="table-wrap"><table><thead><tr><th>Name</th><th>Status</th><th>Featured</th><th>Order</th><th/></tr></thead><tbody>{items.map(x=><tr key={x._id}><td><b>{x.title||x.name||x.clientName}</b><small>{x.slug||x.company||'—'}</small></td><td><span className={`status status--${x.status||'published'}`}>{x.status||'published'}</span></td><td>{x.isFeatured?'Yes':'—'}</td><td>{x.displayOrder??'—'}</td><td><Link to={`/admin/${type}/${x._id}/edit`}>Edit</Link></td></tr>)}</tbody></table></div>:<EmptyState>No {config.label.toLowerCase()} yet. Start by creating one.</EmptyState>}</section>}
export function Editor(){const {type,id}=useParams(),config=collectionConfig[type],navigate=useNavigate();const [item,setItem]=useState({status:'draft',displayOrder:0,isFeatured:false});const [busy,setBusy]=useState(false);useEffect(()=>{if(id)api.get(`/admin/${type}/${id}`).then(r=>setItem(r.data.data)).catch(()=>{});},[type,id]);if(!config)return <Navigate to="/admin"/>;const submit=async e=>{e.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget));values.isFeatured=values.isFeatured==='on';values.displayOrder=Number(values.displayOrder||0);try{if(id) await api.patch(`/admin/${type}/${id}`,values);else await api.post(`/admin/${type}`,values);navigate(`/admin/${type}`)}finally{setBusy(false)}};const del=async()=>{if(confirm(`Delete this ${config.singular.toLowerCase()}? This cannot be undone.`)){await api.delete(`/admin/${type}/${id}`);navigate(`/admin/${type}`)}};const textFields=['description','challenge','objective','strategy','execution','results','review','bio','benefits','deliverables','process','faq','servicesProvided','metrics','testimonial','seoDescription'];return <section className="admin-page"><div className="admin-title"><div><p>CONTENT MANAGEMENT</p><h1>{id?'Edit':'New'} {config.singular}</h1></div><Link to={`/admin/${type}`}>Cancel</Link></div><p className="editor-help">Use the Media Library to upload an image, then paste its secure URL into an image field. For list fields, enter one item per line.</p><form className="editor-form" onSubmit={submit}>{config.fields.map(f=>{let val=item[f]??(f==='status'?'draft':'');if(Array.isArray(val))val=val.map(entry=>typeof entry==='string'?entry:JSON.stringify(entry)).join('\n');if(f==='isFeatured')return <label className="toggle" key={f}><input type="checkbox" name={f} defaultChecked={Boolean(val)}/><span/>Feature on homepage</label>;if(f==='status')return <label key={f}>Status<select name={f} defaultValue={val}><option>draft</option><option>published</option><option>archived</option></select></label>;if(textFields.includes(f))return <label className="wide" key={f}>{f.replace(/([A-Z])/g,' $1')}<textarea name={f} defaultValue={val} rows="5"/></label>;return <label key={f}>{f.replace(/([A-Z])/g,' $1')}<input name={f} type={f==='projectDate'?'date':f==='rating'||f==='displayOrder'?'number':'text'} defaultValue={val} required={['title','name','clientName'].includes(f)}/></label>})}<div className="editor-actions"><Button type="submit" disabled={busy}>{busy?'Saving…':'Save changes'}</Button>{id&&<button type="button" className="danger" onClick={del}>Delete {config.singular}</button>}</div></form></section>}
export function Leads(){
  const [items,setItems]=useState(null);
  const [selected,setSelected]=useState([]);
  const [busy,setBusy]=useState(false);
  useEffect(()=>{api.get('/admin/leads').then(r=>setItems(r.data.data.items||[])).catch(()=>setItems([]));},[]);
  const toggle=id=>setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  const toggleAll=()=>setSelected(current=>current.length===items.length?[]:items.map(item=>item._id));
  const deleteSelected=async()=>{if(!selected.length||!confirm(`Delete ${selected.length} selected inquiry${selected.length===1?'':'ies'}? This cannot be undone.`))return;setBusy(true);try{await api.delete('/admin/leads',{data:{ids:selected}});setItems(current=>current.filter(item=>!selected.includes(item._id)));setSelected([])}catch(error){alert(error.response?.data?.message||'Unable to delete the selected inquiries.')}finally{setBusy(false)}};
  return <section className="admin-page"><div className="admin-title"><div><p>INQUIRIES</p><h1>Contact leads</h1></div>{selected.length>0&&<button type="button" className="danger" onClick={deleteSelected} disabled={busy}>{busy?'Deleting…':`Delete selected (${selected.length})`}</button>}</div>{items===null?<div className="admin-panel">Loading leads…</div>:items.length?<div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all inquiries" checked={selected.length===items.length} onChange={toggleAll}/></th><th>Name</th><th>Contact</th><th>Service</th><th>Status</th></tr></thead><tbody>{items.map(x=><tr key={x._id}><td><input type="checkbox" aria-label={`Select inquiry from ${x.name}`} checked={selected.includes(x._id)} onChange={()=>toggle(x._id)}/></td><td><b>{x.name}</b><small>{x.company||'—'}</small></td><td>{x.email}<small>{x.phone}</small></td><td>{x.service||'—'}</td><td><span className={`status status--${x.status}`}>{x.status}</span></td></tr>)}</tbody></table></div>:<EmptyState>No inquiries yet.</EmptyState>}</section>}
export function SettingsPage(){const [saved,setSaved]=useState(false);const [item,setItem]=useState({});useEffect(()=>{api.get('/settings').then(r=>setItem(r.data.data||{})).catch(()=>{});},[]);const submit=async e=>{e.preventDefault();await api.put('/admin/settings',Object.fromEntries(new FormData(e.currentTarget)));setSaved(true)};return <section className="admin-page"><div className="admin-title"><div><p>CONFIGURATION</p><h1>Site settings</h1></div></div><form className="editor-form" onSubmit={submit}>{['companyName','tagline','description','phone','whatsapp','email','address','googleMapsUrl','instagram','linkedin','facebook','youtube','officeHours','defaultSeoTitle','defaultSeoDescription'].map(f=><label key={f} className={['description','address','defaultSeoDescription'].includes(f)?'wide':''}>{f.replace(/([A-Z])/g,' $1')}<input name={f} defaultValue={item[f]||''}/></label>)}<Button type="submit">{saved?'Saved':'Save settings'}</Button></form></section>}
export function MediaLibrary(){
  const [file,setFile]=useState(null),[folder,setFolder]=useState('general'),[busy,setBusy]=useState(false),[uploaded,setUploaded]=useState(null),[error,setError]=useState('');
  const [projects,setProjects]=useState([]),[projectId,setProjectId]=useState(''),[placement,setPlacement]=useState('thumbnailUrl'),[publishProject,setPublishProject]=useState(true),[assignedProject,setAssignedProject]=useState('');
  useEffect(()=>{
    if(folder!=='projects')return;
    api.get('/admin/projects?limit=100').then(response=>{
      const saved=response.data.data.items||[];
      setProjects([...saved,...websiteProjects.filter(project=>!saved.some(item=>item.slug===project.slug)).map(project=>({...project,isWebsiteProject:true}))]);
    }).catch(()=>setProjects(websiteProjects.map(project=>({...project,isWebsiteProject:true}))));
  },[folder]);
  const changeFolder=value=>{setFolder(value);setProjectId('');setAssignedProject('');setError('');};
  const submit=async event=>{
    event.preventDefault();
    if(!file)return;
    if(folder==='projects'&&!projectId){setError('Choose the project that should use this image.');return;}
    setBusy(true);setError('');setAssignedProject('');
    const form=new FormData();form.append('image',file);form.append('folder',folder);
    try{
      const response=await api.post('/admin/upload',form);
      const asset=response.data.data;
      if(folder==='projects'){
        const project=projects.find(item=>item._id===projectId);
        const values={[placement]:asset.url};
        if(publishProject)values.status='published';
        if(project?.isWebsiteProject){
          const created=await api.post('/admin/projects',{name:project.name,client:project.client,slug:project.slug,category:project.category,shortDescription:project.shortDescription,servicesProvided:project.servicesProvided||[],isFeatured:true,...values});
          setProjects(current=>current.map(item=>item._id===projectId?created.data.data:item));
        }else await api.patch(`/admin/projects/${projectId}`,values);
        setAssignedProject(project?.name||'the selected project');
      }
      setUploaded(asset);
    }catch(e){setError(e.response?.data?.message||'Upload failed. Check your Cloudinary setup.');}
    finally{setBusy(false)}
  };
  const copy=()=>navigator.clipboard?.writeText(uploaded.url);
  return <section className="admin-page"><div className="admin-title"><div><p>ASSET MANAGEMENT</p><h1>Media library</h1></div></div><div className="admin-panel media-library"><h2>Upload an approved image</h2><p>JPEG, PNG, WebP or AVIF only, up to 5 MB. Project images can be assigned directly to the website here—no URL copying is needed.</p><form onSubmit={submit}><label>Cloudinary folder<select value={folder} onChange={event=>changeFolder(event.target.value)}>{['general','services','projects','case-studies','clients','team','testimonials'].map(value=><option key={value}>{value}</option>)}</select></label>{folder==='projects'&&<><label>Project to update<select value={projectId} onChange={event=>setProjectId(event.target.value)} required><option value="">Choose a project</option>{projects.map(project=><option key={project._id} value={project._id}>{project.name}{project.isWebsiteProject?'':' (saved)'}</option>)}</select></label><label>Image placement<select value={placement} onChange={event=>setPlacement(event.target.value)}><option value="thumbnailUrl">Portfolio card image</option><option value="heroImageUrl">Project detail hero image</option></select></label><label className="media-library__publish"><input type="checkbox" checked={publishProject} onChange={event=>setPublishProject(event.target.checked)}/> Show this project on the website</label></>}<label className="media-library__file"><Upload/><span>{file?file.name:'Choose image'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={event=>setFile(event.target.files?.[0])}/></label><Button type="submit" disabled={!file||busy}>{busy?'Uploading…':'Upload image'}</Button></form>{error&&<p className="form-error">{error}</p>}{uploaded&&<div className="media-library__result"><img src={uploaded.url} alt={uploaded.alt||'Uploaded media'}/><div><b>{assignedProject?`Uploaded and assigned to ${assignedProject}.`:'Upload complete'}</b>{assignedProject?<p>Your selected project image is now connected to the website.</p>:<><input value={uploaded.url} readOnly/><button onClick={copy}><Copy size={15}/> Copy URL</button></>}</div></div>}</div></section>}
export function Account(){const user=useAuth();return <section className="admin-page"><div className="admin-title"><div><p>ACCOUNT</p><h1>Admin account</h1></div></div><div className="admin-panel account-panel"><UserCircle/><div><h2>{user?.name}</h2><p>{user?.email}</p><span className="status status--published">{user?.role}</span></div><p>Account credentials are protected server-side. Contact a superadmin to change access permissions or credentials.</p></div></section>}
